package org.maplibre.compose.testing

import kotlin.io.encoding.Base64

/**
 * A 724-byte TrueType font generated for these tests. It maps `A` and `B` to a filled box that
 * covers the whole em square, so any pixel inside a drawn glyph is the text colour.
 */
internal val BOX_FONT: ByteArray by lazy {
  Base64.decode(
    "AAEAAAAKAIAAAwAgT1MvMkUhRLsAAAEoAAAAYGNtYXAADACVAAABlAAAADRnbHlmY5EsJwAAAdAAAABOaGVhZC/H3cQAAACs" +
      "AAAANmhoZWEGQgJbAAAA5AAAACRobXR4BXgAAAAAAYgAAAAKbG9jYQAaADQAAAHIAAAACG1heHAABQAGAAABCAAAACBuYW1l" +
      "99xfNwAAAiAAAACKcG9zdAApACUAAAKsAAAAKAABAAAAAQAA7M85c18PPPUAAQPoAAAAAObJTUYAAAAA5slNRgAA/zgDIAMg" +
      "AAAAAwACAAAAAAAAAAEAAAMg/zgAAAMgAAAAAAMgAAEAAAAAAAAAAAAAAAAAAAACAAEAAAADAAQAAQAAAAAAAgAAAAAAAAAA" +
      "AAAAAAAAAAAAAwLdAZAABQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAPz8/PwAA" +
      "AEEAQgMg/zgAAAMgAMgAAAAAAAAAAAAAAAAAAAAgAAACWAAAAyAAAAAAAAAAAAACAAAAAwAAABQAAwABAAAAFAAEACAAAAAE" +
      "AAQAAQAAAEL//wAAAEH////AAAEAAAAAAAAADQAaACcAAQAyAAACJgK8AAMAADMRIREyAfQCvP1EAAABAAD/OAMgAyAAAwAA" +
      "FREhEQMgyAPo/BgAAAEAAP84AyADIAADAAAVESERAyDIA+j8GAAAAAAAAAQANgABAAAAAAABABUAAAABAAAAAAACAAcAFQAD" +
      "AAEECQABACoAHAADAAEECQACAA4ARk1hcExpYnJlIENvbXBvc2UgVGVzdFJlZ3VsYXIATQBhAHAATABpAGIAcgBlACAAQwBv" +
      "AG0AcABvAHMAZQAgAFQAZQBzAHQAUgBlAGcAdQBsAGEAcgAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAA" +
      "ACQAJQ=="
  )
}
