name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    # Optional: Filter by PR author
    if: |
      github.event.pull_request.user.login == 'sargunv'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          use_sticky_comment: true

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request for potential bugs or issues:
            - Logic errors and oversights
            - Platform-specific issues (Android, iOS, Web, Desktop compatibility)
            - State management bugs in Compose code
            - Memory leaks or resource management issues
            - Breaking changes to public APIs

            Only comment if you find actual issues. Do not comment on code style, formatting, or
            subjective improvements.

            Be constructive and helpful in your feedback.

          # Optional: Add specific tools for running tests or linting
          allowed_tools: "Bash(./gradlew:*)"
